apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: merrykaris/resultserver13
        name: resultserver13
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: servers-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        # env:
        # - name: MYSQL_DATABASE
        #   value: "phonebook"
        # - name: MYSQL_USER
        #   value: "clarus"
        # - name: MYSQL_PASSWORD
        #   value: "Clarusway_1"  
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql
        resources: {}

